__import__('pysqlite3')
import sys
sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')
import streamlit as st
from langchain_community.document_loaders import WebBaseLoader
from chains import Chain
from portfolio import Portfolio
from utils import clean_text

# Configure the Streamlit page
st.set_page_config(
    layout="wide",
    page_title="Cloud Email Generator",
    page_icon="📧"
)

def sidebar():
    """
    Sets up the sidebar with a logo, title, description, and step-by-step guide.
    """
    st.sidebar.image(
        r'imgs/img.png',
        use_column_width=True
    )

    st.sidebar.markdown("""
        <style>
        .sidebar-title {
            text-align: center;
            font-size: 34px;
            font-weight: bold;
        }
        </style>
        <div class="sidebar-title">
            Cloud Email Generator
        </div>
        """, unsafe_allow_html=True)

    st.sidebar.markdown("""
        <style>
        .sidebar-description {
            text-align: center;
            font-size: 20px;
            margin-top: 20px;
        }
        .sidebar-steps {
            text-align: left;
            font-size: 18px;
            margin-top: 20px;
            line-height: 1.6;
        }
        </style>
        <div class="sidebar-description">
            This tool helps you generate personalized cold emails quickly and effectively. 
            Input your details, and let the AI do the rest, crafting compelling messages 
            tailored to your needs.
        </div>
        <div class="sidebar-steps">
            <h3>How It Works:</h3>
            <ol>
                <li><strong>Provide Details:</strong> Enter a valid URL or a job description into the input field.</li>
                <li><strong>Processing:</strong> The tool will load and process the information, cleaning and extracting key details.</li>
                <li><strong>AI Analysis:</strong> The AI will analyze the extracted details and generate a list of relevant job postings.</li>
                <li><strong>Skill Matching:</strong> The tool will match required skills with your portfolio and provide useful links.</li>
                <li><strong>Email Draft:</strong> Review and customize the email draft generated by the AI, tailored to the job postings.</li>
            </ol>
        </div>
        """, unsafe_allow_html=True)

def display_chat_history():
    """
    Displays the chat history stored in the session state with stickers and copy buttons.
    """
    user_sticker = "imgs/user.png"  # Path to user sticker
    bot_sticker = "imgs/bot.png"    # Path to bot sticker

    if "chat_history" in st.session_state:
        for entry in st.session_state.chat_history:
            if entry['role'] == 'User':
                col1, col2 = st.columns([1, 4])
                with col1:
                    st.image(user_sticker, width=30)  # Adjust width as needed
                with col2:
                    st.markdown(f"**User:** {entry['message']}")
                   
            elif entry['role'] == 'Bot':
                col1, col2 = st.columns([1, 4])
                with col1:
                    st.image(bot_sticker, width=30)  # Adjust width as needed
                with col2:
                    st.markdown(f"**Bot:** {entry['message']}")
               

def copy_to_clipboard(text):
    """
    Copies the given text to the clipboard.
    """
    st.write(f'<script>navigator.clipboard.writeText("{text}");</script>', unsafe_allow_html=True)

def create_streamlit_app(llm, portfolio, clean_text):
    """
    Sets up the main functionality of the Streamlit app.
    
    Parameters:
    - llm: Language model instance (e.g., Chain object).
    - portfolio: Instance of the Portfolio class.
    - clean_text: Function for cleaning up text.
    """
    # Initialize chat history in session state
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []

    # Input field for URL or plain text
    user_input = st.chat_input("Please provide a valid URL or job description:")

    if user_input:
        # Add user message to chat history
        st.session_state.chat_history.append({"role": "User", "message": user_input})
        
        try:
            if user_input.startswith(('http://', 'https://')):
                # Load and process data from URL
                loader = WebBaseLoader([user_input])
                page_content = loader.load().pop().page_content
                data = clean_text(page_content)
            else:
                # Use the provided plain text
                data = clean_text(user_input)
            
            # Load portfolio and extract job details
            portfolio.load_portfolio()
            jobs = llm.extract_jobs(data)
            
            if jobs:
                for job in jobs:
                    # Extract required skills and query portfolio
                    skills = job.get('skills', [])
                    links = portfolio.query_links(skills)
                    
                    # Generate email draft
                    email = llm.write_mail(job, links)
                    
                    # Add bot message to chat history
                    st.session_state.chat_history.append({"role": "Bot", "message": email})
            else:
                st.warning("Warning: No job postings were found in the content you provided. Please ensure that your submission includes valid information and includes the following details: role, experience, skills, and description.")
                
        except Exception as e:
            st.error(f"An error occurred: {e}")
            st.session_state.chat_history.append({"role": "Bot", "message": f"An error occurred: {e}"})

    # Display chat history
    display_chat_history()

if __name__ == "__main__":
    # Initialize components
    chain = Chain()
    portfolio = Portfolio()
    
    # Display sidebar
    sidebar()
    
    # Run the Streamlit app
    create_streamlit_app(chain, portfolio, clean_text)
